CREATE TABLE student (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200)
);

CREATE TABLE PERMISSIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE USER_ROLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE PER_ROLE_MAP (
    pid INT,
    rid INT,
    status BOOLEAN DEFAULT TRUE,
    PRIMARY KEY(pid, rid),
    FOREIGN KEY(pid) REFERENCES PERMISSIONS(id),
    FOREIGN KEY(rid) REFERENCES USER_ROLES(id)
);


CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    pass VARCHAR(255) NOT NULL -- Consider using a more secure method for storing passwords
);


CREATE TABLE USER_ROLES_MAP (
    uid INT,
    rid INT,
    PRIMARY KEY(uid, rid),
    FOREIGN KEY(uid) REFERENCES USERS(id),
    FOREIGN KEY(rid) REFERENCES USER_ROLES(id)
);
